import type { Metadata } from "next";
import {
  Afacad_Flux,
  Averia_Serif_Libre,
  Geist,
  Geist_Mono,
  Poiret_One,
  Share_Tech,
  Share_Tech_Mono,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const california = Averia_Serif_Libre({
  variable: "--font-california",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const outatime = Share_Tech({
  variable: "--font-outatime",
  weight: ["400"],
  subsets: ["latin"],
});

const goldenState = Afacad_Flux({
  variable: "--font-golden-state",
  weight: ["400", "500"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outatime.variable} ${california.variable} ${goldenState.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
